#!/usr/bin/expect -f
set timeout -1
set password [lindex $argv 0]

spawn ssh -o StrictHostKeyChecking=no -p 14126 root@103.242.3.87 "ufw --force reset && ufw default deny incoming && ufw default allow outgoing && ufw allow 14126/tcp && ufw allow 3000/tcp && ufw allow 3001/tcp && ufw allow 80/tcp && ufw allow 443/tcp && ufw --force enable && ufw status verbose"
expect {
    "*yes/no*" { send "yes\r"; exp_continue }
    "*assword:*" { send "$password\r"; exp_continue }
    eof
}
