export const CATDESK_TOKENS = {
  bgBase: '#0e0e10',
  bgSurface: '#17171a',
  bgSelected: '#1c2a3d',
  border: '#2a2a2f',
  textPrimary: '#e6e6e6',
  textSecondary: '#9a9a9f',
  accent: '#3b82f6',
  up: '#22c55e',
  down: '#ef4444',
  fontSans: 'Inter, -apple-system, sans-serif',
  fontMono: 'JetBrains Mono, monospace',
  fontMd: '14px',
  radiusMd: '6px',
  space: [0, 4, 8, 12, 16, 24, 32, 48, 64],
  siderWidth: '220px',
  kpiHeight: '56px',
} as const;

export const CSS_VARS: Record<string, string> = {
  '--cd-bg-base': CATDESK_TOKENS.bgBase,
  '--cd-bg-surface': CATDESK_TOKENS.bgSurface,
  '--cd-bg-selected': CATDESK_TOKENS.bgSelected,
  '--cd-border': CATDESK_TOKENS.border,
  '--cd-text-primary': CATDESK_TOKENS.textPrimary,
  '--cd-text-secondary': CATDESK_TOKENS.textSecondary,
  '--cd-accent': CATDESK_TOKENS.accent,
  '--cd-up': CATDESK_TOKENS.up,
  '--cd-down': CATDESK_TOKENS.down,
  '--cd-font-sans': CATDESK_TOKENS.fontSans,
  '--cd-font-mono': CATDESK_TOKENS.fontMono,
  '--cd-font-md': CATDESK_TOKENS.fontMd,
  '--cd-radius-md': CATDESK_TOKENS.radiusMd,
  '--cd-sider-w': CATDESK_TOKENS.siderWidth,
  '--cd-kpi-h': CATDESK_TOKENS.kpiHeight,
};
