export const CATDESK_TOKENS = {
  bgBase: '#fff8ec',
  bgSurface: '#fffdf7',
  bgSelected: '#ffe8df',
  border: '#dccdc0',
  textPrimary: '#2e2520',
  textSecondary: '#786960',
  accent: '#f05d5e',
  up: '#16856b',
  down: '#d64d5f',
  fontSans: '"Avenir Next", "Nunito Sans", "PingFang SC", "Microsoft YaHei", sans-serif',
  fontMono: '"IBM Plex Mono", "SFMono-Regular", Consolas, monospace',
  fontMd: '14px',
  radiusMd: '12px',
  space: [0, 4, 8, 12, 16, 24, 32, 48, 64],
  siderWidth: '252px',
  kpiHeight: '56px',
} as const;

export const CSS_VARS: Record<string, string> = {
  '--cd-bg-base': CATDESK_TOKENS.bgBase,
  '--cd-bg-surface': CATDESK_TOKENS.bgSurface,
  '--cd-bg-selected': CATDESK_TOKENS.bgSelected,
  '--cd-border': CATDESK_TOKENS.border,
  '--cd-text-primary': CATDESK_TOKENS.textPrimary,
  '--cd-text-secondary': CATDESK_TOKENS.textSecondary,
  '--cd-accent': CATDESK_TOKENS.accent,
  '--cd-up': CATDESK_TOKENS.up,
  '--cd-down': CATDESK_TOKENS.down,
  '--cd-font-sans': CATDESK_TOKENS.fontSans,
  '--cd-font-mono': CATDESK_TOKENS.fontMono,
  '--cd-font-md': CATDESK_TOKENS.fontMd,
  '--cd-radius-md': CATDESK_TOKENS.radiusMd,
  '--cd-sider-w': CATDESK_TOKENS.siderWidth,
  '--cd-kpi-h': CATDESK_TOKENS.kpiHeight,
  '--cd-ink': '#302621',
  '--cd-cocoa': '#2d2420',
  '--cd-coral': '#f05d5e',
  '--cd-mint': '#5ec4ae',
  '--cd-sun': '#f3bd4f',
  '--cd-lilac': '#8c7be8',
  '--cd-paper': '#fffdf7',
};
