export const RUNTIME_SCHEMA_TABLES = [
  'stocks',
  'daily_bars',
  'backtest_results',
  'trades',
  'users',
  'favorite_stocks',
  'data_update_logs',
  'scheduled_tasks',
  'task_execution_logs',
  'feishu_notification_outbox',
  'notification_incident_states',
  'daily_screeners',
  'paper_trading_portfolios',
  'paper_trading_positions',
  'paper_trading_trades',
  'paper_trading_snapshots',
  'research_trading_loop_runs',
  'research_trading_loop_decisions',
  'paper_trading_order_intents',
  'paper_trading_order_intent_outcomes',
  'paper_trading_canary_review_snapshots',
  'risk_alerts',
  'trading_journals',
  'portfolio_simulations',
  'data_source_health',
  'ai_investment_signals',
  'recommendation_trade_outcomes',
  'recommendation_loop_policy_snapshots',
  'budget_policy_version_snapshots',
  'quant_strategies',
  'stock_fundamental_factors',
  'stock_money_flow_factors',
  'stock_valuation_factors',
  'quant_backtest_tasks',
  'quant_backtest_results',
  'quant_backtest_trades',
  'quant_signals',
  'quant_strategy_performance_snapshots',
  'quant_strategy_weights',
  'quant_strategy_experiments',
  'quant_strategy_param_versions',
  'quant_strategy_param_validations',
  'quant_fusion_audits',
  'task_parameter_audit_logs',
  'realtime_quotes',
] as const;

export const CRITICAL_RUNTIME_SCHEMA_TABLES = [
  'scheduled_tasks',
  'task_execution_logs',
  'feishu_notification_outbox',
  'notification_incident_states',
  'ai_investment_signals',
  'recommendation_trade_outcomes',
  'recommendation_loop_policy_snapshots',
  'quant_signals',
  'quant_fusion_audits',
  'quant_backtest_tasks',
  'quant_backtest_results',
  'quant_strategy_weights',
  'quant_strategy_experiments',
  'quant_strategy_param_versions',
  'quant_strategy_param_validations',
  'stock_fundamental_factors',
  'stock_money_flow_factors',
  'stock_valuation_factors',
  'realtime_quotes',
  'paper_trading_portfolios',
  'paper_trading_trades',
  'research_trading_loop_runs',
  'research_trading_loop_decisions',
  'paper_trading_order_intents',
  'paper_trading_order_intent_outcomes',
  'paper_trading_canary_review_snapshots',
  'task_parameter_audit_logs',
] as const;

export const RUNTIME_SCHEMA_REQUIRED_COLUMNS: Record<
  string,
  { critical: boolean; columns: string[] }
> = {
  quant_strategies: {
    critical: true,
    columns: [
      'strategy_key',
      'default_params',
      'execution_policy',
      'environment_policy',
      'lifecycle_policy',
      'notes',
      'display_order',
    ],
  },
  quant_signals: {
    critical: true,
    columns: [
      'trade_date',
      'symbol',
      'strategy_key',
      'signal',
      'score',
      'raw_factors',
      'agent_eligible',
      'agent_status',
    ],
  },
  ai_investment_signals: {
    critical: true,
    columns: [
      'source_type',
      'source_id',
      'loop_run_id',
      'signal_date',
      'metadata',
      'current_price',
    ],
  },
  recommendation_trade_outcomes: {
    critical: true,
    columns: ['signal_id', 'symbol', 'trade_status', 'loop_run_id', 'metadata'],
  },
  paper_trading_order_intents: {
    critical: true,
    columns: ['portfolio_id', 'symbol', 'side', 'status', 'intent_date', 'metadata'],
  },
  paper_trading_portfolios: {
    critical: true,
    columns: ['user_id', 'portfolio_type', 'current_cash', 'total_value', 'is_active'],
  },
  research_trading_loop_runs: {
    critical: true,
    columns: ['user_id', 'portfolio_id', 'trading_day', 'research_day', 'status', 'summary'],
  },
  research_trading_loop_decisions: {
    critical: true,
    columns: ['run_id', 'portfolio_id', 'symbol', 'action', 'status', 'sources', 'reason'],
  },
  paper_trading_order_intent_outcomes: {
    critical: true,
    columns: ['intent_id', 'portfolio_id', 'symbol', 'evaluation_status', 'horizons'],
  },
  paper_trading_canary_review_snapshots: {
    critical: true,
    columns: [
      'generated_at',
      'snapshot_date',
      'status',
      'action',
      'review_score',
      'closed_count',
      'review',
    ],
  },
  scheduled_tasks: {
    critical: true,
    columns: ['type', 'cron_expression', 'is_active', 'parameters', 'last_run_status'],
  },
  task_execution_logs: {
    critical: true,
    columns: [
      'task_id',
      'task_name',
      'status',
      'total_items',
      'completed_items',
      'failed_items',
      'result_summary',
    ],
  },
  risk_alerts: {
    critical: true,
    columns: ['user_id', 'symbol', 'level', 'message', 'rule_id', 'is_read', 'metadata'],
  },
  feishu_notification_outbox: {
    critical: true,
    columns: [
      'idempotency_key',
      'topic_key',
      'audience',
      'status',
      'attempts',
      'max_attempts',
      'next_attempt_at',
      'payload',
    ],
  },
  notification_incident_states: {
    critical: true,
    columns: [
      'source_key',
      'status',
      'generation',
      'occurrence_count',
      'opened_notification_generation',
      'recovered_notification_generation',
    ],
  },
  stock_fundamental_factors: {
    critical: true,
    columns: ['symbol', 'factor_date', 'source'],
  },
  stock_money_flow_factors: {
    critical: true,
    columns: ['symbol', 'factor_date', 'source'],
  },
  stock_valuation_factors: {
    critical: true,
    columns: ['symbol', 'factor_date', 'source'],
  },
  realtime_quotes: {
    critical: true,
    columns: ['symbol', 'trade_date', 'quote_time', 'current_price'],
  },
};
