export const RUNTIME_SCHEMA_TABLES = [
  'stocks',
  'daily_bars',
  'backtest_results',
  'trades',
  'users',
  'favorite_stocks',
  'data_update_logs',
  'scheduled_tasks',
  'task_execution_logs',
  'daily_screeners',
  'paper_trading_portfolios',
  'paper_trading_positions',
  'paper_trading_trades',
  'paper_trading_snapshots',
  'risk_alerts',
  'trading_journals',
  'portfolio_simulations',
  'data_source_health',
  'ai_investment_signals',
  'recommendation_trade_outcomes',
  'recommendation_loop_policy_snapshots',
  'budget_policy_version_snapshots',
  'quant_strategies',
  'quant_backtest_tasks',
  'quant_backtest_results',
  'quant_backtest_trades',
  'quant_signals',
  'quant_strategy_performance_snapshots',
  'quant_strategy_weights',
  'quant_fusion_audits',
  'task_parameter_audit_logs',
  'realtime_quotes',
] as const;

export const CRITICAL_RUNTIME_SCHEMA_TABLES = [
  'scheduled_tasks',
  'task_execution_logs',
  'ai_investment_signals',
  'recommendation_trade_outcomes',
  'recommendation_loop_policy_snapshots',
  'quant_signals',
  'quant_fusion_audits',
  'quant_backtest_tasks',
  'quant_backtest_results',
  'quant_strategy_weights',
  'realtime_quotes',
  'paper_trading_portfolios',
  'paper_trading_trades',
  'task_parameter_audit_logs',
] as const;
